#!/bin/sh
set -e

case "$1" in
    configure)
      chown -R www-data /var/www/dgi-db/
      sudo gem install bundler
      cd /var/www/dgi-db && sudo -u www-data RAILS_ENV=production bundle exec rake -f /var/www/dgi-db/Rakefile db:schema:load && cd -
      sudo -u postgres psql -d dgidb -f /var/www/dgi-db/db/data.sql
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
