name: Unit Tests
on:
  push:
    branches:
      -master
      -staging
    pull_request:

jobs:
  tests:
    name: Tests
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        ruby: [2.5, 2.6]
    services:
        postgres:
          image: postgres:12
          env:
            POSTGRES_USER: postgres
            POSTGRES_DB: dgidb_test
            POSTGRES_PASSWORD: 'ci'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Setup Ruby'
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: Setup DB
        env:
          CI_BUILD: true
          RAILS_ENV: test
        run: bundle exec rake db:create db:structure:load db:test:prepare

      - name: Run Tests
        env:
          RAILS_ENV: test
          CI_BUILD: true
        run: bundle exec rake spec

